name: Label PR Release Impact
description: Labels a PR based on the semantic-release impact of their commits
inputs:
  github-token:
    description: 'token for GitHub operations, use secrets.GITHUB_TOKEN or github.token'
    required: true
  patch-label:
    description: label to apply for a patch release (-.-.x)
    required: true
  minor-label:
    description: label to apply for a minor release (-.x.-)
    required: true
  major-label:
    description: label to apply for a major release (x.-.-)
    required: true
  no-label:
    description: label to apply for no release
    required: true
  # milliseconds:  # id of input
  #   description: number of milliseconds to wait
  #   required: true
  #   default: '1000'
outputs:
  semantic-release-result:
    description: 'the version bump needed: "patch", "minor", "major", or "no-release"'
  label:
    description: 'the label chosen'
runs:
  using: node12
  main: dist/index.js
branding:
  icon: tag
  color: orange
