name: tests

on:
  # pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   INPUT_GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #- run: npm run test:coverage
  # test action works running from the graph
  # try-it:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: ./
  #     with:
  #       milliseconds: 1000
